### ISSUE TITLE
Issue while pushing the app: "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by ichandan16** [pivotalservices/app-metrics-nozzle#6]
Hi,
When we try to push the application with below buildpack:

`https://github.com/cloudfoundry/go-buildpack.git#v1.8.20`
We are getting error:

```
2018-03-12T12:08:53.854-04:00 [APP/PROC/WEB/0] [OUT] [negroni] listening on :8080
2018-03-12T12:08:54.106-04:00 [APP/PROC/WEB/0] [ERR] panic: runtime error: invalid memory address or nil pointer dereference
2018-03-12T12:08:54.106-04:00 [APP/PROC/WEB/0] [ERR] goroutine 1 [running]:
2018-03-12T12:08:54.106-04:00 [APP/PROC/WEB/0] [ERR] /tmp/contents875067462/deps/0/go1.6.4/go/src/runtime/panic.go:481 +0x3ea
2018-03-12T12:08:54.106-04:00 [APP/PROC/WEB/0] [ERR] /tmp/gobuildpack.gopath090757915/.go/src/app-metrics-nozzle/main.go:85 +0xe6a
2018-03-12T12:08:54.106-04:00 [APP/PROC/WEB/0] [ERR] [signal 0xb code=0x1 addr=0x0 pc=0x555ef778711a]
2018-03-12T12:08:54.106-04:00 [APP/PROC/WEB/0] [ERR] main.main()
```
Appreciate any help.

Thanks,
Chandan

**Comment by jtuchscherer** [comment]
Which version of the CF CLI are you using? If it is older than 6.24 you will have compatibility issues. 
This line [here](https://github.com/pivotalservices/app-metrics-nozzle/blob/master/main.go#L85) only works with v6.24 and up. The DopplerEndpoint property has been introduced in that version - previously it has been called LoggregatorEndpoint. See here: https://github.com/cloudfoundry/cli/tree/master/plugin/plugin_examples#changes-in-v6240
